### ISSUE TITLE
Hello, install the plug-in bestest_markdown_editor to report errors

### ISSUE THREAD

**Issue by peixiaoqing** [LeviticusMB/bestest_markdown_editor#7]
redmine：4.0.0
ruby： 2.3.8

Hello, installation plug-in bestest_markdown_editor error reporting, lack of modules, how to install this module, I used “gem install alias_method_chain  ”，But it's still a mistake.

detailed information：
implement：rake redmine:plugins:migrate NAME=bestest_markdown_editor RAILS_ENV=production
rake aborted!

bash-4.2# rake redmine:plugins:migrate NAME=bestest_markdown_editor RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ApplicationHelper:Module
Did you mean?  alias_method
/radmin/apps/redmine/htdocs/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:10:in `block in included'
/radmin/apps/redmine/htdocs/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:8:in `class_eval'
/radmin/apps/redmine/htdocs/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:8:in `included'
/radmin/apps/redmine/htdocs/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:34:in `include'
/radmin/apps/redmine/htdocs/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:34:in `<top (required)>'
/radmin/apps/redmine/htdocs/plugins/bestest_markdown_editor/init.rb:1:in `<top (required)>'
/radmin/apps/redmine/htdocs/lib/redmine/plugin.rb:173:in `block in load'
/radmin/apps/redmine/htdocs/lib/redmine/plugin.rb:164:in `each'
/radmin/apps/redmine/htdocs/lib/redmine/plugin.rb:164:in `load'
/radmin/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in `<top (required)>'
/radmin/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by paulvi** [comment]
Redmine default plugins folder is `redmine/plugins`

README recommended way is to clone into that folder

新年快乐！Happy Chinese New Year!
