### ISSUE TITLE
In rails 5.2.2, redmine4.0.1 , it's report errors: NoMethodError: undefined method `alias_method_chain' for ApplicationHelper:Module

### ISSUE THREAD

**Issue by shiqiangguo** [LeviticusMB/bestest_markdown_editor#9]
My environment's info :  
$ ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
$ rails -v
Rails 5.2.2
$ bundle version
Bundler version 2.0.1 (2019-01-04 commit d7ad2192f)
$ gem -v
3.0.1
$ mysql 
Server version: 5.7.25 MySQL Community Server (GPL)
mysql > 

$  bundle exec rake convert_textile_to_markdown RAILS_ENV=production
(in /usr/local/redmine-4.0.1)
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ApplicationHelper:Module
Did you mean?  alias_method
/usr/local/redmine-4.0.1/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:10:in `block in included'
/usr/local/redmine-4.0.1/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:8:in `class_eval'
/usr/local/redmine-4.0.1/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:8:in `included'
/usr/local/redmine-4.0.1/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:34:in `include'
/usr/local/redmine-4.0.1/plugins/bestest_markdown_editor/lib/bestest_markdown_editor/patches/application_helper_patch.rb:34:in `<top (required)>'
/usr/local/redmine-4.0.1/plugins/bestest_markdown_editor/init.rb:1:in `<top (required)>'
/usr/local/redmine-4.0.1/lib/redmine/plugin.rb:173:in `block in load'
/usr/local/redmine-4.0.1/lib/redmine/plugin.rb:164:in `each'
/usr/local/redmine-4.0.1/lib/redmine/plugin.rb:164:in `load'
/usr/local/redmine-4.0.1/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/redmine-4.0.1/config/environment.rb:14:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => convert_textile_to_markdown => environment
(See full trace by running task with --trace)

**Comment by cowrycoin** [comment]
Hi shiqiangguo,

looks like this app is not compatible with redmine 4.0 yet.

Did you solved this topic. Maybe you can help me or you made a patch?

**Comment by jankokert** [comment]
I tried it with Redmine 4.2 and I get the same error. Please can someone fix that bug?  The plugin is exactly what I need!
